added Alee problem with solution
neatudarius/pa pull request #32
Opened 2020-06-05 09:37 UTC by mzzmara

added solution for Alee - Infoarena with detailed explanation on why the chosen algorithm fits this kind of problem

2020-06-12 05:24 UTC, neatudarius requested changes

2020-06-12 05:24 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +
Have you run clang-format?

2020-06-12 05:24 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +// Alee - Drumuri minime in graf
### ### 
```suggestion
// alee - Drumuri minime in graf
```

2020-06-12 05:24 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +	std::vector<std::vector<char>> graph;
Please run clang-format to fix indentation problems

2020-06-12 05:24 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +        std::vector<std::pair<int, int>> directions;
We can declare this as `const` and initialization with `{ {1, 0}, {0, 1}, {-1, 0}, {0, -1}}`

2020-06-12 05:24 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +		std::queue<std::pair<int, int>> nodeQueue;
Please rename this to `q` to be consistent with the theory example.

Same for `minPath` -> `d`.

2020-06-12 05:24 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +			nodeQueue.pop();
This should be moved right after line 79.

2020-06-12 05:24 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +    std::ifstream fin("custi.in");
typo?

2020-06-12 05:24 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +    std::ofstream fout("custi.out");
typo?

2020-06-12 05:24 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/main.cpp
> +// Copyright 2020 Nicolae Mara-Ioana <maraioana9967@gmail.com>
Please check that you have a duplicate source code. Delete alee.cpp and if the reported issues are still available, fix them in main.cpp

2020-08-13 09:07 UTC, neatudarius requested changes

2020-08-13 09:07 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/Makefile
> +	rm -f *.o *.exe *.out
```suggestion
	rm -f *.o *.exe *.out

```

2020-08-13 09:07 UTC, neatudarius commented on lab/skel_graph/traversal/problems/alee/_example.in
> +1 1 8 8
```suggestion
1 1 8 8

```

2020-09-07 16:01 UTC, RaduNichita commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +        graph = std::vector<std::vector<char>>(n + 1,
I think we should keep the convention and replace graph with adj. @neatudarius what do you think?

2020-09-07 16:03 UTC, RaduNichita commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +			for (auto& dir : directions) {
Can you use c++17 and structured bindings, please? That means for (auto &[dx, dy]: directions ?

2020-09-07 16:05 UTC, RaduNichita commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +        if (p1.first + p2.first <= n && p1.first + p2.first >= 1
Maybe here we can directly return the result? I mean return (condition1 && condition2 && condition3 && condition4) ?

2020-09-07 16:06 UTC, RaduNichita commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +}
```suggestion

}
```

2020-09-07 16:06 UTC, RaduNichita commented on lab/skel_graph/traversal/problems/alee/alee.in
> +1 1 8 8
```suggestion
1 1 8 8

```

2020-09-07 16:07 UTC, RaduNichita commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +// Copyright 2020 Nicolae Mara-Ioana <maraioana9967@gmail.com>
Please remove this file and apply the suggestions made in main.cpp, as @neatudarius you have duplicate file

2020-09-07 16:08 UTC, RaduNichita commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +	int n;
I think we can have int n, m,  source;

2020-09-07 16:10 UTC, RaduNichita commented on lab/skel_graph/traversal/problems/alee/alee.cpp
> +			graph[x][y] = 'T';
I think it's may be a bit complicated to have 'T' and ' '. Maybe change to boolean and have 1 for tree and 0 for no tree?

2024-12-12 23:36 UTC, merged